### ISSUE TITLE
User의 이메일 인증에 관한 Issue

### ISSUE THREAD

**Issue by HelloNaks** [entertainmentAmongUs/entertainmentAmongUs#12]
현재 User의 이메일로 인증 코드를 보내는 것은 구현이 되었으나, 인증 코드가 맞는지 확인하는 작업에서 오류가 발생합니다.
인증 코드를 항상 랜덤 함수를 돌려서 인증하려고 해도 랜덤이 한번 더 돌아서 인증이 불가능 합니다.
아래의 두 가지 방법중 어떤게 나을지 고민부탁드립니다.
1) User table에 code(string) 추가하여 메일로 전해 받은 code를 맞는지 확인
2) (code, userId)를 저장하는 table 하나를 추가하여 이메일 보내기를 누른 사람만 테이블에 저장.

**Comment by Lieutenant-K** [comment]
1번 방법이 더 나아보입니다~
2번 방법은 사용자가 인증할때마다 실행해야할 작업이 많아보입니다. (데이터 추가 및 삭제 작업)

**Comment by ngj1014** [comment]
저도 1번이 나은듯 하네요.

**Comment by HelloNaks** [comment]
1번 방법으로 진행하겠습니다.
