### ISSUE TITLE
User 관련 Rest API 수정 관련 Issue

### ISSUE THREAD

**Issue by HelloNaks** [entertainmentAmongUs/entertainmentAmongUs#13]
Rest API에서 로그인, 인증하기 method를 POST로 바꿔야 할 듯 합니다.
POST나 PUT을 해야 client에서 Server로 데이터를 받을 수 있습니다.
검색을 통해 확인해보니 로그인은 POST를 하는 경우가 대부분이라 POST로 하는 것이 좋을듯 합니다.

**Comment by ngj1014** [comment]
알겠습니다.. 노션도 제가 바꿔놓을게여.
