### ISSUE TITLE
Profile Rest API 변경 관련

### ISSUE THREAD

**Issue by HelloNaks** [entertainmentAmongUs/entertainmentAmongUs#17]
Profile 관련 Rest API 수정 관련 Issue
    - Rest API에서 Profile 관련해서 Get방식의 Http 메소드를 사용하면 Client로부터 값을 받아오지 못하거나 header로 받아와야 하기 때문에 URI에 {userId}를 추가하여 client로부터 userId를 받아올 수 있게 변경하는것이 어떨까합니다.
    
    ex) /profile/mypage → /profile/mypage/{userId} (userId는 본인의 아이디)
    
    ex) /profile/list-up→ /profile/list-up/{userId} (userId는 상대방의 아이디)

**Comment by Lieutenant-K** [comment]
profiles/{profileid}/user-info 이런식으로 바꾸면 의미가 더 직관적이라 좋을 것 같습니다. 

그리고 두 기능은 사실상 조회하는 유저의 id만 다르기 때문에 굳이 uri에 부가적인 다른 정보를 넣을 필요가 없어보이네요~
