### ISSUE TITLE
Lobby, WaittingRoom에서의 소켓 관련 기능에 대한 이슈

### ISSUE THREAD

**Issue by Lieutenant-K** [entertainmentAmongUs/entertainmentAmongUs#26]
1. Lobby에서 접속 종료(disconnect) 시 서버에서 "connectedUserList" 이벤트 송신이 안되는 문제
-> 서버에서 해당 이벤트를 보내는 코드가 누락된 것으로 보임.

2. Lobby의 방 리스트에 각 방의 현재 인원을 표시하는 기능을 구현해야하는 문제
-> 서버에서 "joinRoom" 또는 "leaveRoom" 이벤트 수신 시 방의 현재 인원을 수정하고 "roomList" 이벤트를 회신하는 방법으로 구현 가능
단, 모든 방에서 인원이 변경될때마다 이벤트를 보내므로 비효율적인 방법으로 보이는데 추가 의견 부탁드립니다.

3. 방 생성 시 방의 userList에 유저 데이터가 중복으로 추가되는 문제
-> 방 생성 시 서버에 "joinRoom" 이벤트를  보내야 userList를 받을 수 있기 때문에 서버에서 "newRoom" 이벤트 송신 시 userList 데이터를 보내는 것으로 해결 가능한데 아예 이벤트를 변경하지 않고 해결할 수 있을 것으로 보입니다. 추가 의견 부탁드립니다.

4. WaittingRoom 퇴장 시 userList에 유저 데이터가 남아있는 문제
-> 1번과 마찬가지로 퇴장한 유저를 리스트에서 삭제하는 코드가 누락된 것으로 보임.

5. 추가적으로 방장 id를 방 정보 안에 포함시키는 것에 대한 의견을 구합니다
-> 방장 id만 알면 나머지 유저들이 isHost 데이터를 갖고 있지 않아도 되기 때문에 더 좋은 방법이라고 생각됩니다.

**Comment by Kyun2da** [comment]
@Lieutenant-K 님 좀 늦었습니다 🙏  
> 1.Lobby에서 접속 종료(disconnect) 시 서버에서 "connectedUserList" 이벤트 송신이 안되는 문제

**이건 토요일 저녁까지 고쳐놓을게요~**

> 2. Lobby의 방 리스트에 각 방의 현재 인원을 표시하는 기능을 구현해야하는 문제

**실시간 연동은 너무나 비효율적인것 같고 유저가 새로고침버튼으로 컨트롤 하거나 매 초마다 자동으로 새로고침되게 하는것은 어떨까요?**

> 3. 방 생성 시 방의 userList에 유저 데이터가 중복으로 추가되는 문제

```방 생성 시 서버에 "joinRoom" 이벤트를 보내야 userList를 받을 수 있기 때문에``` <- 이부분 자체가 문제인 것 같아요.
방안의 정보를 받는 이벤트를 추가하는건 어떨까요?(ex. roomInfo)

> 4. WaittingRoom 퇴장 시 userList에 유저 데이터가 남아있는 문제

**이것도 토요일 저녁까지 고쳐놓을게요~**

> 5. 추가적으로 방장 id를 방 정보 안에 포함시키는 것에 대한 의견을 구합니다

**좋은 것 같네요~ 엄밀히 말하면 방장아이디는 유저데이터보다는 방정보 데이터에 좀더 가까운 것 같아요~**
